version: "3.9"

services:
  web:
    build: docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    volumes:
      - ./src:/var/www/html
